### ISSUE TITLE
interface circuit

### ISSUE THREAD

**Issue by santon74** [laszlodaniel/J1850VPWCore#1]
Hello,
I have a basic question, not an issue.  Will this library work with a simple 3 transistor interface (the circuit published by Matafonoff in his library)?
Thanks,
Anton.

**Comment by laszlodaniel** [comment]
Hi, yes, it should work. Select the correct active level state when initializing the library. IIRC it's ACTIVE_HIGH.

**Comment by santon74** [comment]
Thank you,
The 3 transistor interface is inverting.  So, the ACTIVE_HIGH will pull the Tx to HIGH and result in LOW at the J1850 bus?
I am thinking about building an optocoupler intrface instead of that thansistor circuit.  With one optocoupler and one transistor, I think I can make a non-nverting circuit.  In that case, I suppose the initialization must be ACTIVE_LOW?

**Comment by laszlodaniel** [comment]
"ACTIVE" refers to HIGH state of J1850 bus. "HIGH/LOW" refers to RX/TX pin state.

When ACTIVE_HIGH mode is selected the bus goes to HIGH state when TX is HIGH. Bus logic state mirrors TX state. This is preferred.
ACTIVE_LOW on the other hand inverts TX logic: when TX is LOW, bus is HIGH.

Matafonoff's circuit is non-inverting, works with ACTIVE_HIGH setting, so it's a good starting point.

**Comment by santon74** [comment]
Thanks!

**Comment by santon74** [comment]
Hi Laszlo,
May I ask you one more question?
My sketch works OK outside of the car. However, in car, the Arduino sometimes freezes. It is not because of the noisy environment of the car since it happens with the engine off. Also, I added some filtering capacitors, a diode and a choke to 12V line. Still, the Arduino freezes. I think it happens because of the overflow at the pin 2. As I understood, the library is using the INT 0 of Arduino UNO (pin 2). Is there something that could be done to prevent the freezing?
Thanks.

**Comment by laszlodaniel** [comment]
Hi, we have never encountered freezing while using this library in other projects (in-vehicle). I suggest keeping the receiver callback function short. So avoid updating LCD or printing large texts to Serial in the callback. Instead, save message to a global variable, set a bool flag, let the callback finish promptly, and check the set flag in the loop() function. While the loop deals with your tasks the library can work efficiently in the background.

Also please open a new issue for individual questions.
