### ISSUE TITLE
Several message filters

### ISSUE THREAD

**Issue by santon74** [laszlodaniel/J1850VPWCore#2]
Hello,
I am using your library for some projects on my old Chevrolet; thank you for this excellent library!
I have a question: is there a possibility to use two or more message filters?  For example, I am currently searching for the particular message and use a filter with a specific header.  Can I create a second "uintt8_t messageFilter[]" variable to filter for two types of messages with different headers?
Thanks!

**Comment by laszlodaniel** [comment]
Hi, multiple filter definition is not possible with current implementation. Having one definition should be enough if I understand your goal correctly. Write header (ID) bytes in a comma separated list, like in the J1850VPWFilter.ino example, and the library will filter incoming messages by those starting bytes.

**Comment by santon74** [comment]
Thank you for your reply.  I am trying to search for 2 types of messages, one has the header 68 EA 10 0A, while the second one has the header C8 3B 10 10.  Do you suggest to write the filter as: uint8_t messageFilter[] = {0x68, 0xEA, 0x10, 0x0A, 0xC8, 0x3B, 0x10, 0x10}?  I did the following and, surprisingly, it seems working: I created two messages:
uint8_t messageFilter_gear = {0x68, 0xEA, 0x10, 0x0A};
uint8_t messageFilter_atf = {0xC8, 0x3B, 0x10, 0x1};

**Comment by laszlodaniel** [comment]
I see it now. The filter feature does not support multi-byte headers. This is unexpected.
In your case I would filter by "0x68, 0xC8" and further narrow the results in the message received callback function by the rest of the header bytes.
Or don't use filters at all and simply run the received message bytes through so called "guard clauses":

```
void PCIMessageReceived(uint8_t* message, uint8_t messageLength)
{
    if (((message[0] != 0x68) && (message[1] != 0xEA) && (message[2] != 0x10) && (message[3] != 0x0A)) ||
        ((message[0] != 0xC8) && (message[1] != 0x3B) && (message[2] != 0x10) && (message[3] != 0x01)))
    {
        return; // do not proceed
    }

    // Process message
}
```

**Comment by santon74** [comment]
Excellent, thank you!

**Comment by santon74** [comment]
Hi Laszlo,
Can I ask another question?  I noticed that the Arduino freezes sometimes.  Could it be related to the high baud rate (250000)?  The J1850 transmission baud rate is only 10.4, I think.  Do you think reducing of the baud rate can help?

**Comment by laszlodaniel** [comment]
Baudrate is most likely not the issue here.

**Comment by santon74** [comment]
Hi Laszlo,
May I ask you one more question?  
My sketch works OK outside of the car.  However, in car, the Arduino sometimes freezes.  It is not because of the noisy environment of the car since it happens with the engine off.  Also, I added some filtering capacitors, a diode and a choke to 12V line.  Still, the Arduino freezes.  I think it happens because of the overflow at the pin 2.  As I understood, the library is using the INT 0 of Arduino UNO (pin 2).  Is there something that could be done to prevent the freezing?
Thanks.
